version: "3"
services:
        mnist:
        # replace username/repo:tag with your name and image details
                image: mnist:1.0
                deploy:
                        replicas: 1
                        restart_policy:
                                condition: on-failure
                        resources:
                                limits:
                                        cpus: "1"
                                        memory: 15935M
                ports:
                        - "80:80"
                environment:
                        MNIST_ENV: development
                volumes:
                        - "/mnt/sda1/var/lib/docker/volumes/myvol/_data:/app/logs"
        visualizer:
                image: dockersamples/visualizer:stable
                ports:
                        - "8080:8080"
                volumes:
                        - "/var/run/docker.sock:/var/run/docker.sock"
                deploy:
                        placement:
                                constraints: [node.role == manager]
                networks:
                        - webnet
        tensorboard:
                image: fstcap/tensorboard:1.2
                deploy:
                        placement:
                                constraints: [node.role == manager]
                ports:
                        - "6006:6006"
                volumes:
                        - "/mnt/sda1/var/lib/docker/volumes/myvol/_data/scalars:/app/logs/scalars"
                networks:
                        - webnet
networks:
        webnet:
