version: "3.7"
services:
        mnist:
        # replace username/repo:tag with your name and image details
                build: .
                environment:
                        MODELS: "cnn"
                        METHODS: "train"
                volumes:
                        - data_volume:/app/logs
        tensorboard:
                image: fstcap/tensorboard:1.2
                ports:
                        - "6006:6006"
                volumes:
                        - data_volume:/app/logs
                networks:
                        - webnet
networks:
        webnet:

volumes:
        data_volume:
